/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package Form;

import DB.DBAccess;
import Form.frmOTP;
import chatapp.EmailSender;
import Form.frmRegister ;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.security.SecureRandom;
import java.sql.SQLException;

/**
 *
 * @author DELL
 */
public class frmOTP extends javax.swing.JFrame {
    private int userId;

    /** Creates new form frmOTP */
    public frmOTP() {
        initComponents();
    }
    public frmOTP(int userId) {
        if (userId <= 0) {
            throw new IllegalArgumentException("UserID không hợp lệ!");
        }
        initComponents();
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtotp = new javax.swing.JTextField();
        btnxacnhan = new javax.swing.JButton();
        btnguilai = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnxacnhan.setText("Xác Nhận");
        btnxacnhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxacnhanActionPerformed(evt);
            }
        });

        btnguilai.setText("Gửi Lại");
        btnguilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguilaiActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Nhập Mã OTP");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtotp, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(btnxacnhan)
                        .addGap(158, 158, 158)
                        .addComponent(btnguilai)))
                .addContainerGap(134, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtotp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnxacnhan)
                    .addComponent(btnguilai))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnxacnhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxacnhanActionPerformed
       String otp = txtotp.getText();

if (otp.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Vui lòng nhập mã OTP!");
    return;
}

try {
    DBAccess db = new DBAccess();
    
    // Kiểm tra thông tin nhập vào
    System.out.println("UserID: " + userId + ", OTP: " + otp);

    // Truy vấn OTP từ cơ sở dữ liệu
    String query = "SELECT * FROM OTPs WHERE UserID = ? AND OTPCode = ? AND ExpiryTime > CURRENT_TIMESTAMP AND IsUsed = FALSE";
    PreparedStatement stmt = db.getConnection().prepareStatement(query);
    stmt.setInt(1, userId);
    stmt.setString(2, otp);
    ResultSet rs = stmt.executeQuery();

    if (rs.next()) {
        // Cập nhật trạng thái xác minh người dùng
        String updateUserQuery = "UPDATE Users SET IsVerified = TRUE WHERE UserID = ?";
        PreparedStatement updateUserStmt = db.getConnection().prepareStatement(updateUserQuery);
        updateUserStmt.setInt(1, userId);
        updateUserStmt.executeUpdate();

        // Đánh dấu OTP đã sử dụng
        String updateOtpQuery = "UPDATE OTPs SET IsUsed = TRUE WHERE OTPID = ?";
        PreparedStatement updateOtpStmt = db.getConnection().prepareStatement(updateOtpQuery);
        updateOtpStmt.setInt(1, rs.getInt("OTPID"));
        updateOtpStmt.executeUpdate();

        JOptionPane.showMessageDialog(this, "Xác minh thành công!");
        this.dispose();
    } else {
        JOptionPane.showMessageDialog(this, "Mã OTP không hợp lệ hoặc đã hết hạn!");
        System.out.println("Không tìm thấy OTP hợp lệ.");
    }

    db.close();
} catch (SQLException sqle) {
    JOptionPane.showMessageDialog(this, "Lỗi cơ sở dữ liệu: " + sqle.getMessage());
    sqle.printStackTrace();
} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Lỗi: " + e.getMessage());
    e.printStackTrace();
}
    }//GEN-LAST:event_btnxacnhanActionPerformed

    private void btnguilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguilaiActionPerformed
        try {
        String otp = String.format("%06d", new java.util.Random().nextInt(1000000));
        long expiryTime = System.currentTimeMillis() + 5 * 60 * 1000; // 5 phút

        DBAccess db = new DBAccess();
        String query = "UPDATE OTPs SET OTPCode = '" + otp + "', ExpiryTime = '"
                + new java.sql.Timestamp(expiryTime) + "', IsUsed = FALSE WHERE UserID = " + userId;
        int result = db.Update(query);

        if (result > 0) {
            JOptionPane.showMessageDialog(this, "Mã OTP mới đã được gửi tới email của bạn!");
        } else {
            JOptionPane.showMessageDialog(this, "Lỗi khi gửi lại mã OTP.");
        }

        db.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Lỗi: " + e.getMessage());
    }
    }//GEN-LAST:event_btnguilaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmOTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmOTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmOTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmOTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmOTP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnguilai;
    private javax.swing.JButton btnxacnhan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtotp;
    // End of variables declaration//GEN-END:variables

}
