/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Form;

import DB.DBAccess;
import chatapp.EmailSender;
import Form.frmRegister;
import chatapp.OTPManager;
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.Timer;

/**
 *
 * @author DELL
 */
public class frmOTP extends javax.swing.JFrame {
    private String tenHienThi, tenDangNhap, matKhau;
     private Timer countdownTimer;
    private int countdownTime = 5 * 60;
    
    /**
     * Creates new form frmOTP
     */
    public frmOTP() {
        initComponents();
         startCountdown();
    }

     public frmOTP(String tenHienThi, String tenDangNhap, String matKhau) {
        this.tenHienThi = tenHienThi;
        this.tenDangNhap = tenDangNhap;
        this.matKhau = matKhau;

        initComponents();
    }
    private void startCountdown() {
        countdownTimer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (countdownTime > 0) {
                    countdownTime--;
                    updateCountdownLabel();
                } else {
                    countdownTimer.stop(); // Stop the timer when countdown reaches 0
                    JOptionPane.showMessageDialog(null, "Mã OTP đã hết hạn!");
                }
            }
        });
        countdownTimer.start();
    }
    private void updateCountdownLabel() {
        int minutes = countdownTime / 60;
        int seconds = countdownTime % 60;
        String timeText = String.format("Thời gian còn lại: %02d:%02d", minutes, seconds);
        lblCountdown.setText(timeText); // Assuming lblCountdown is the label showing the countdown
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtotp = new javax.swing.JTextField();
        btnxacnhan = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblCountdown = new javax.swing.JLabel();
        btnguilai = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 255, 204));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        txtotp.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnxacnhan.setBackground(new java.awt.Color(0, 51, 255));
        btnxacnhan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnxacnhan.setForeground(new java.awt.Color(255, 255, 255));
        btnxacnhan.setText("Xác Nhận");
        btnxacnhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxacnhanActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Kiểm tra mail của bạn để nhận mã OTP");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Xác minh Gmail của bạn ");

        btnguilai.setFont(new java.awt.Font("Segoe UI", 3, 10)); // NOI18N
        btnguilai.setForeground(new java.awt.Color(255, 51, 51));
        btnguilai.setText("Gửi Lại");
        btnguilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguilaiActionPerformed(evt);
            }
        });

        jLabel3.setText("Nếu chưa nhận được mail, nhấn");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(btnxacnhan))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnguilai))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCountdown, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtotp, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtotp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnxacnhan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCountdown, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnguilai)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnxacnhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxacnhanActionPerformed
       String otpInput = txtotp.getText().trim();

        if (otpInput.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã OTP!");
            return;
        }

        if (System.currentTimeMillis() > OTPManager.otpExpiryTime) {
            JOptionPane.showMessageDialog(this, "Mã OTP đã hết hạn!");
        } else if (otpInput.equals(OTPManager.generatedOtp)) {
            JOptionPane.showMessageDialog(this, "Xác nhận OTP thành công!");

            try {
                // Lưu thông tin tài khoản vào cơ sở dữ liệu
                DBAccess db = new DBAccess();
                String query = "INSERT INTO Users (DisplayName, Username, PasswordHash, Email, IsVerified) VALUES (?, ?, ?, ?, TRUE)";
                PreparedStatement stmt = db.getConnection().prepareStatement(query);
                stmt.setString(1, tenHienThi);
                stmt.setString(2, tenDangNhap);
                stmt.setString(3, matKhau);
                stmt.setString(4, OTPManager.email);

                stmt.executeUpdate();
                JOptionPane.showMessageDialog(this, "Đăng ký thành công!");
                this.dispose();  
            frmLogin loginForm = new frmLogin(); 
            loginForm.setVisible(true);

                this.dispose();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Lỗi CSDL: " + e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Mã OTP không chính xác!");
        }
    
    }//GEN-LAST:event_btnxacnhanActionPerformed

    private void btnguilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguilaiActionPerformed
       try {
        // Tạo lại OTP mới
        String newOtp = String.format("%06d", new java.util.Random().nextInt(1000000));
        OTPManager.generatedOtp = newOtp; // Cập nhật mã OTP mới
        OTPManager.otpExpiryTime = System.currentTimeMillis() + 5 * 60 * 1000; // Đặt lại thời gian hết hạn (5 phút)

        // Lấy email người dùng từ cơ sở dữ liệu
        DBAccess db = new DBAccess();
        String query = "SELECT Email FROM Users WHERE Username = ?";
        PreparedStatement stmt = db.getConnection().prepareStatement(query);
        stmt.setString(1, tenDangNhap);
        ResultSet rs = stmt.executeQuery();

        if (rs.next()) {
            String email = rs.getString("Email");

            // Gửi OTP mới qua email
            EmailSender.sendEmail(email, "Mã OTP của bạn", "Mã OTP mới của bạn là: " + newOtp + ". Mã này hết hạn sau 5 phút.");

            // Thông báo đã gửi OTP mới
            JOptionPane.showMessageDialog(this, "Mã OTP mới đã được gửi đến email của bạn!");
            startCountdown(); // Bắt đầu đếm ngược khi gửi lại OTP

        } else {
            JOptionPane.showMessageDialog(this, "Không tìm thấy email người dùng!");
        }

        db.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Lỗi khi gửi lại OTP: " + e.getMessage());
    }
    }//GEN-LAST:event_btnguilaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmOTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmOTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmOTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmOTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmOTP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnguilai;
    private javax.swing.JButton btnxacnhan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCountdown;
    private javax.swing.JTextField txtotp;
    // End of variables declaration//GEN-END:variables

}
